### ISSUE TITLE
🚀[Feature]: Have the option of not deleting prereleases

### ISSUE THREAD

**Issue by mchave3** [PSModule/Publish-PSModule#46]
### Description

In connection with Process-PSModule, would it be possible to have an option not to delete prereleases in the Github release list ? 
I think it would be nice to have the choice of keeping them or not, so as to have at least a history of changes in Github.

**Comment by MariusStorhaug** [comment]
Im been planniing a while to just bundle the entire `Process-PSModule` into one repo and have the features and stuff there instead of having separate repos. Makes it easier to follow it as one process. 
All the actions have the same lifecycle and are deeply dependent on eachother.

What would make sense here to me, is a settingsfile that the Process-PSModule uses for controling what the different stages do:

```yml
Settings:
  Testing:
  - SourceCode:
      PesterSettingsFile:
  - Module:
      PesterSettingsFile:
  Build:
    PublishArtifactWithRelease: true
  Documentation:
    PrereleaseDocumentation: false
  Publishing:
    AutocleanupPrereleases: true
```

This would make it easy to have all the settings in one place, track the issues in one place and make development of the process better. With this, adding feature flags would be somewhat easier, rather than having to use the inputs on the workflow. Thoughts?
